environment:
  nodejs_version: 6.5.0

platform:
  - x86

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build_script:
#  - cmd: node index.js arduino-builder
  - cmd: node index.js avrdude
#  - cmd: node index.js avr-gcc

test_script:
  - node --version
  - npm --version
